# Generated by Django 5.0 on 2024-01-12 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_profile_email_profile_first_last_profile_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_last',
            new_name='last_name',
        ),
    ]
