# Generated by Django 5.0 on 2024-01-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_profile_following'),
        ('blog', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(to='blog.comment'),
        ),
    ]
