# Generated by Django 5.0 on 2024-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_profile_comments'),
        ('blog', '0004_alter_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', to='blog.comment'),
        ),
    ]
