# Generated by Django 4.2.9 on 2024-02-07 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='posts',
            field=models.ManyToManyField(related_name='post_tags', to='blog.post'),
        ),
    ]
